# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Project Pythia Cookbook Template
author: the <a href="https://projectpythia.org/">Project Pythia</a> Community
logo: notebooks/images/logos/pythia_logo-white-rtext.svg
copyright: "2024"

execute:
  # To execute notebooks via a Binder instead, replace 'cache' with 'binder'
  execute_notebooks: cache
  timeout: 600
  allow_errors: False # cells with expected failures must set the `raises-exception` cell tag

# Add a few extensions to help with parsing content
parse:
  myst_enable_extensions: # default extensions to enable in the myst parser. See https://myst-parser.readthedocs.io/en/latest/using/syntax-optional.html
    - amsmath
    - colon_fence
    - deflist
    - dollarmath
    - html_admonition
    - html_image
    - replacements
    - smartquotes
    - substitution

sphinx:
  config:
    linkcheck_ignore: ["https://doi.org/*", "https://zenodo.org/badge/*"] # don't run link checker on DOI links since they are immutable
    nb_execution_raise_on_error: true # raise exception in build if there are notebook errors (this flag is ignored if building on binder)
    html_favicon: notebooks/images/icons/favicon.ico
    html_last_updated_fmt: "%-d %B %Y"
    html_theme: sphinx_pythia_theme
    html_permalinks_icon: '<i class="fas fa-link"></i>'
    html_theme_options:
      home_page_in_toc: true
      repository_url: https://github.com/ProjectPythia/cookbook-template/ # Online location of your book
      repository_branch: main # Which branch of the repository should be used when creating links (optional)
      use_issues_button: true
      use_repository_button: true
      use_edit_page_button: true
      use_fullscreen_button: true
      analytics:
        google_analytics_id: G-T52X8HNYE8
      github_url: https://github.com/ProjectPythia
      twitter_url: https://twitter.com/project_pythia
      icon_links:
        - name: YouTube
          url: https://www.youtube.com/channel/UCoZPBqJal5uKpO8ZiwzavCw
          icon: fab fa-youtube-square
          type: fontawesome
      launch_buttons:
        binderhub_url: https://binder.projectpythia.org
        notebook_interface: jupyterlab
      logo:
        link: https://projectpythia.org
      navbar_start:
        - navbar-logo
      navbar_end:
        - navbar-icon-links
      navbar_links:
        - name: Home
          url: https://projectpythia.org
        - name: Foundations
          url: https://foundations.projectpythia.org
        - name: Cookbooks
          url: https://cookbooks.projectpythia.org
        - name: Resources
          url: https://projectpythia.org/resource-gallery.html
        - name: Community
          url: https://projectpythia.org/index.html#join-us
      footer_logos:
        NCAR: notebooks/images/logos/NSF-NCAR_Lockup-UCAR-Dark_102523.svg
        Unidata: notebooks/images/logos/Unidata_logo_horizontal_1200x300.svg
        UAlbany: notebooks/images/logos/UAlbany-A2-logo-purple-gold.svg
      footer_start:
        - footer-logos
        - footer-info
        - footer-extra
